import clsx from 'clsx';
import { Poppins } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

import AuthSessionProvider from '@/src/providers/authSessionProvider';
import AuthWatcher from '@/src/components/auth/auth-watcher';
import { ThemeProvider } from '@/src/providers/theme-provider';
import { Toaster } from 'sonner';
import SocialAuthWrapper from '@/src/components/auth/social-auth-wrapper';
import { AuthProvider } from '@/src/context/AuthContext';
import QueryProvider from '@/src/providers/query-provider';
import { WalletProvider } from '@/src/context/WalletContext';

export const metadata: Metadata = {
  title: 'FreshLaundry',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
});

// import SocialAuthWrapper from '@/src/components/auth/social-auth-wrapper';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/icons/purwadhika.jpg' sizes='any' />
      </head>
      <body className={clsx(poppins.variable, 'antialiased')}>
        <AuthSessionProvider>
          <AuthProvider>
            <SocialAuthWrapper>
              <AuthWatcher />
              <ThemeProvider
                attribute='class'
                defaultTheme='system'
                enableSystem
                disableTransitionOnChange
              >
                <QueryProvider>
                  <WalletProvider>{children}</WalletProvider>
                </QueryProvider>
              </ThemeProvider>
            </SocialAuthWrapper>
          </AuthProvider>
        </AuthSessionProvider>
        <Toaster richColors position='top-right' />
      </body>
    </html>
  );
}
