import clsx from 'clsx';
import { Poppins } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

import AuthSessionProvider from '@/src/providers/authSessionProvider';
import AuthWatcher from '@/src/components/authWatcher';
import { ThemeProvider } from '@/src/providers/theme-provider';
import { WashingMachine } from 'lucide-react';
// import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'FreshLaundry',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
});

// import SocialAuthWrapper from '@/src/components/auth/social-auth-wrapper';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/icons/purwadhika.jpg' sizes='any' />
      </head>
      <body className={clsx(poppins.variable, 'antialiased')}>
        <AuthSessionProvider>
          {/* <SocialAuthWrapper> */}
          <AuthWatcher />
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          {/* </SocialAuthWrapper> */}
        </AuthSessionProvider>
        {/* <Toaster richColors position='top-right' /> */}
      </body>
    </html>
  );
}
